baseURL = "https://qeden.dev/"
languageCode = "en-us"
title = "qeden.dev"

[module.hugoVersion]
extended = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
# hl_Lines = ""
hl_inline = false
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = false
style = "github-dark"
tabWidth = 4
wrapperClass = "highlight"

[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = false

[params.theme_config]
appearance = "auto"
back_home_text = ".."
date_format = "2006-01-02"
isListGroupByDate = false
isShowFooter = false
